### ISSUE TITLE
Be able to reset the application

### ISSUE THREAD

**Issue by cheikhKebeDia** [ferrannp/fithero#123]
I think it can be nice to have the ability to delete all the application data and restart from 0, instead of deleting exercice one by one

**Comment by cheikhKebeDia** [comment]
The use case I was thinking about is when you change your workout program and want to start your tracking from 0. But yeah, maybe this is not a clever idea.
In the setting you can just offload the application, they can't erase the workout you tracked via the app.

On the other hand, yes, a button to delete a whole exercice or workout will make sense.

**Comment by ferrannp** [comment]
I'll open one issue for deleting the whole workout and another for the whole exercise (to keep them smaller). Thank you!
