### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by leonardo2204** [ferrannp/fithero#126]
Hey @ferrannp, first of all, cool app man, really looking forward to contributing to this!
Do you have any plan to write a backend to sync all stuff up, have a "workout database", workout plans etc?

Thanks for your time!

**Comment by ferrannp** [comment]
Hey! Thank you :)

I do not have a plan for having a backend on the cloud. For now the predefined exercises are coming from an npm package (json file) that I need to open source too when I have a moment to do it: https://github.com/ferrannp/fithero/issues/112. Then, you can also add your own exercises.

The "database" is locally, you can also backup and restore it. What I want to add is automatic backup.

So yeah, for now I do not plan to have such cloud backend (I guess that is what you meant) as that would require tones of extra work and possibly a paid plan somewhere.

**Comment by leonardo2204** [comment]
@ferrannp Cool, that's exactly what I meant!
Yeah, the paying problem really sucks, another nice approach regarding new exercises (and search) is [Algolia](https://www.algolia.com/pricing/), which is free for open-source projects, is really fast and easy to integrate with React-Native, thus you could open-source the exercise database and import it to Algolia. For new exercises, we could create a PR here that triggers a sync with Algolia and auto-add it to the platform (similar to how [Confs.tech does](https://confs.tech/conferences/new)).
What do you think?

Thanks, man!

**Comment by ferrannp** [comment]
Right now I don't think we need such thing in the app to be honest. I'd like to keep that simple.

Having the exercises locally makes the search instant and we do not need any connection to the net at all.

When the exercise repo is open source, we can merge new exercises and just publish them (if this is done a lot, we can even codepush them).

**Comment by leonardo2204** [comment]
I think you gotta a point here!

Thanks man!
