### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by leonardo2204** [ferrannp/fithero#127]
I've seen that Redux is only being used at the Settings screen.
Don't you think it would make more sense to use more Redux and less state in the app?
We could also use reselect in the future for better performance and predictability.

What do you think?

Thanks man!

**Comment by ferrannp** [comment]
I prefer local state over Redux when possible. Actually, I am thinking to have a `SettingsProvider` and use `Context` and go completely away from Redux as I don't really need it in this app.

Why would you want more Redux?

**Comment by leonardo2204** [comment]
For more predictability and better re-use of some actions (Like services).
IMO using Redux is easier.

________________________________
De: Ferran Negre <notifications@github.com>
Enviado: segunda-feira, 22 de julho de 2019 13:55
Para: ferrannp/fithero <fithero@noreply.github.com>
Cc: Leonardo Ferrari <ferrari2204_5@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [ferrannp/fithero] Redux (#127)


I prefer local state over Redux when possible. Actually, I am thinking to have a SettingsProvider and use Context and go completely away from Redux as I don't really need it in this app.

Why would you want more Redux?

**Comment by ferrannp** [comment]
I agree in some cases it helps but in this app, all the major logic is about Realm and there is already a hook to handle it.

**Comment by leonardo2204** [comment]
I see, my second part of this thread would be exactly that, using redux-sagas to handle Realm events (which is also more "logical" and easily testable), but since there is already a way that handles Realm I'm not sure if it makes sense to drag this discussion any further...

________________________________
De: Ferran Negre <notifications@github.com>
Enviado: segunda-feira, 22 de julho de 2019 14:46
Para: ferrannp/fithero <fithero@noreply.github.com>
Cc: Leonardo Ferrari <ferrari2204_5@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [ferrannp/fithero] Redux (#127)


I agree in some cases it helps but in this app, all the major logic is about Realm and there is already a hook to handle it.
