### ISSUE TITLE
NullPointerException: at android.graphics.drawable.DrawableContainer$DrawableContainerState.createAllFutures

### ISSUE THREAD

**Issue by ferrannp** [ferrannp/fithero#144]
I saw this myself in my own device. Very random. There seems to be a workaround: https://github.com/facebook/react-native/issues/17530

**Comment by ferrannp** [comment]
Hopefully this 3537c416638e7d9f5bffbbdf95dedc6c2c905571 will fix it.

**Comment by saketkumar** [comment]
@ferrannp Is this fixed for you guys in prod?

**Comment by ferrannp** [comment]
I still get some crashes about this... Gotta figure out what is causing it (I think is about `TextInput`).

**Comment by saketkumar** [comment]
@ferrannp the number of crashes is reduced or same as earlier?
